name: '_Build PowerPlatform Solution'

run-name: 'Build PowerPlatform Solution'

on:
  workflow_call:
    inputs:
      shell:
        description: Shell in which you want to run the action (powershell or pwsh)
        required: false
        default: powershell
        type: string
      runsOn:
        description: JSON-formatted string of the types of machine to run the build job on
        required: true
        type: string
      checkoutRef:
        description: Ref to checkout
        required: false
        default: ${{ github.sha }}
        type: string
      project:
        description: Name of the built project
        required: true
        type: string
      projectName:
        description: Friendly name of the built project
        required: true
        type: string
      publishArtifacts:
        description: Flag indicating whether the artifacts should be published
        type: boolean
        default: false
      artifactsNameSuffix:
        description: Suffix to add to the artifacts names
        required: false
        default: ''
        type: string
      parentTelemetryScopeJson:
        description: Specifies the telemetry scope for the telemetry signal
        required: false
        type: string

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Build:
    needs: [ ]
    runs-on: ${{ fromJson(inputs.runsOn) }}
    defaults:
      run:
        shell: ${{ inputs.shell }}
    name: '${{ inputs.projectName }}'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.checkoutRef }}
          lfs: true

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v6.1
        with:
          shell: ${{ inputs.shell }}
          project: ${{ inputs.project }}
          get: type,powerPlatformSolutionFolder,appRevision,appBuild

      - name: Build
        uses: microsoft/AL-Go-Actions/BuildPowerPlatform@v6.1
        with:
          shell: ${{ inputs.shell }}
          solutionFolder: ${{ inputs.project }}
          outputFolder: ${{ inputs.project }}/.buildartifacts/_PowerPlatformSolution/
          outputFileName: ${{ inputs.project }}
          appRevision: ${{ env.appRevision }}
          appBuild: ${{ env.appBuild }}

      - name: Calculate Artifact names
        id: calculateArtifactsNames
        uses: microsoft/AL-Go-Actions/CalculateArtifactNames@v6.1
        if: success() || failure()
        with:
          shell: ${{ inputs.shell }}
          project: ${{ inputs.project }}
          buildMode: 'default'
          suffix: ${{ inputs.artifactsNameSuffix }}

      - name: Publish artifacts - Power Platform Solution
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: inputs.publishArtifacts
        with:
          name: ${{ steps.calculateArtifactsNames.outputs.PowerPlatformSolutionArtifactsName }}
          path: '${{ inputs.project }}/.buildartifacts/_PowerPlatformSolution/'
          if-no-files-found: ignore
