name: 'Cleanup PR Container'

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Pull Request Number'
        required: true
        type: string
  pull_request:
    types: [closed]
    branches: [ main , staging, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || inputs.prNumber }}
  cancel-in-progress: true

defaults:
  run:
    shell: pwsh

permissions:
  actions: read
  contents: read
  id-token: write
  pull-requests: read

jobs:
  Initialization:
    needs: [ ]
    if: (!failure() && !cancelled())
    runs-on: [ windows-latest ]
    outputs:    
      githubRunnerShell: ${{ steps.ReadSettings.outputs.GitHubRunnerShell }}
    steps:
      - name: Dump Workflow Information
        uses: microsoft/AL-Go-Actions/DumpWorkflowInfo@v7.2
        with:
          shell: powershell

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          lfs: true

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v7.2
        with:
          shell: powershell

      - name: Read settings
        id: ReadSettings
        uses: TRASER-Software-GmbH/AL-Go-Actions/ReadSettings@main
        with:
          shell: powershell

  CleanupPRContainer:
    needs: [ Initialization ]
    if: (!failure() && !cancelled())
    runs-on: [ self-hosted ]
    steps:
      - name: Cleanup PR Container
        id: CleanupPRContainer
        uses: TRASER-Software-GmbH/AL-Go-Actions/CleanupBCContainer@main
        with:
          shell: ${{ needs.Initialization.outputs.githubRunnerShell }}
          pullRequestNumber: ${{ github.event.pull_request.number || inputs.prNumber }}