name: ' Create Online Dev. Environment'

run-name: "Create Online Dev. Environment for [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: Name of the online environment
        required: true
      reUseExistingEnvironment:
        description: Reuse environment if it exists
        required: false
        default: 'N'
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: 'N'

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Initialize:
    runs-on: [ windows-latest ]
    outputs:
      deviceCode: ${{ steps.authenticate.outputs.deviceCode }}
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v3.1
        with:
          shell: powershell
          eventId: "DO0093"

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v3.1
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}

      - name: Read secrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v3.1
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          settingsJson: ${{ env.Settings }}
          secrets: 'adminCenterApiCredentials'

      - name: Check AdminCenterApiCredentials / Initiate Device Login (open to see code)
        id: authenticate
        run: |
          $ErrorActionPreference = "STOP"
          Set-StrictMode -version 2.0
          $adminCenterApiCredentials = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($env:adminCenterApiCredentials))
          if ($adminCenterApiCredentials) {
            Write-Host "AdminCenterApiCredentials provided in secret $($ENV:adminCenterApiCredentialsSecretName)!"
            Set-Content -Path $ENV:GITHUB_STEP_SUMMARY -value "Admin Center Api Credentials was provided in a secret called $($ENV:adminCenterApiCredentialsSecretName). Using this information for authentication."
          }
          else {
            Write-Host "AdminCenterApiCredentials not provided, initiating Device Code flow"
            $ALGoHelperPath = "$([System.IO.Path]::GetTempFileName()).ps1"
            $webClient = New-Object System.Net.WebClient
            $webClient.DownloadFile('https://raw.githubusercontent.com/microsoft/AL-Go-Actions/v3.1/AL-Go-Helper.ps1', $ALGoHelperPath)
            . $ALGoHelperPath
            $BcContainerHelperPath = DownloadAndImportBcContainerHelper -baseFolder $ENV:GITHUB_WORKSPACE
            $authContext = New-BcAuthContext -includeDeviceLogin -deviceLoginTimeout ([TimeSpan]::FromSeconds(0))
            CleanupAfterBcContainerHelper -bcContainerHelperPath $bcContainerHelperPath
            Set-Content -Path $ENV:GITHUB_STEP_SUMMARY -value "AL-Go needs access to the Business Central Admin Center Api and could not locate a secret called $($ENV:adminCenterApiCredentialsSecretName) (https://aka.ms/ALGoSettings#AdminCenterApiCredentialsSecretName)`n`n$($authContext.message)"
            Add-Content -Path $env:GITHUB_OUTPUT -Value "deviceCode=$($authContext.deviceCode)"
          }

  CreateDevelopmentEnvironment:
    runs-on: [ windows-latest ]
    name: Create Development Environment
    needs: [ Initialize ]
    env:
      deviceCode: ${{ needs.Initialize.outputs.deviceCode }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v3.1
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ needs.Initialize.outputs.telemetryScopeJson }}

      - name: Read secrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v3.1
        env:
          secrets: ${{ toJson(secrets) }}
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ needs.Initialize.outputs.telemetryScopeJson }}
          settingsJson: ${{ env.Settings }}
          secrets: 'adminCenterApiCredentials'

      - name: Set AdminCenterApiCredentials
        run: |
          if ($env:deviceCode) {
            $adminCenterApiCredentials = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("{""deviceCode"":""$($env:deviceCode)""}"))
            Add-Content -path $env:GITHUB_ENV -value "adminCenterApiCredentials=$adminCenterApiCredentials"
          }

      - name: Create Development Environment
        uses: microsoft/AL-Go-Actions/CreateDevelopmentEnvironment@v3.1
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ needs.Initialize.outputs.telemetryScopeJson }}
          environmentName: ${{ github.event.inputs.environmentName }}
          reUseExistingEnvironment: ${{ github.event.inputs.reUseExistingEnvironment }}
          directCommit: ${{ github.event.inputs.directCommit }}
          adminCenterApiCredentials: ${{ env.adminCenterApiCredentials }}

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@v3.1
        with:
          shell: powershell
          eventId: "DO0093"
          telemetryScopeJson: ${{ needs.Initialize.outputs.telemetryScopeJson }}
