name: 'Create a new app'

run-name: "Create a new app in [${{ github.ref_name }}]"

on:
  workflow_dispatch:
    inputs:
      project:
        description: Project name if the repository is setup for multiple projects
        required: false
        default: '.'
      name:
        description: Name
        required: true      
      publisher:
        description: Publisher
        required: true
      idrange:
        description: ID range (from..to)
        required: true
      sampleCode:
        description: Include Sample code (Y/N)
        required: false
        default: 'Y'
      directCommit:
        description: Direct COMMIT (Y/N)
        required: false
        default: "N"
      useGhTokenWorkflow:
        description: Use GhTokenWorkflow for Pull Request/COMMIT
        type: boolean

permissions:
  contents: write
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  CreateApp:
    runs-on: [ windows-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go/Actions/WorkflowInitialize@f3d69d507d017100a262efb5bd856a7b667a2b19
        with:
          shell: powershell
          eventId: "DO0092"

      - name: Read settings
        uses: microsoft/AL-Go/Actions/ReadSettings@f3d69d507d017100a262efb5bd856a7b667a2b19
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          get: type

      - name: Read secrets
        uses: microsoft/AL-Go/Actions/ReadSecrets@f3d69d507d017100a262efb5bd856a7b667a2b19
        if: github.event.inputs.useGhTokenWorkflow == 'true'
        with:
          shell: powershell
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'

      - name: CalculateToken
        id: CalculateToken
        env:
          useGhTokenWorkflow: ${{ github.event.inputs.useGhTokenWorkflow }}
        run: |
          $ghToken = '${{ secrets.GITHUB_TOKEN }}'
          if ($env:useGhTokenWorkflow -eq 'true') {
            $secrets = $env:Secrets | ConvertFrom-Json
            if ($secrets.GHTOKENWORKFLOW) {
              $ghToken = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($secrets.GHTOKENWORKFLOW))
            }
            else {
              Write-Host "::Warning::GHTOKENWORKFLOW secret not found. Using GITHUB_TOKEN."
            }
          }
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "ghToken=$ghToken"

      - name: Creating a new app
        uses: microsoft/AL-Go/Actions/CreateApp@f3d69d507d017100a262efb5bd856a7b667a2b19
        with:
          shell: powershell
          token: ${{ steps.CalculateToken.outputs.ghToken }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          project: ${{ github.event.inputs.project }}
          type: ${{ env.type }}
          name: ${{ github.event.inputs.name }}
          publisher: ${{ github.event.inputs.publisher }}
          idrange: ${{ github.event.inputs.idrange }}
          sampleCode: ${{ github.event.inputs.sampleCode }}
          directCommit: ${{ github.event.inputs.directCommit }}

      - name: Finalize the workflow
        if: always()
        uses: microsoft/AL-Go/Actions/WorkflowPostProcess@f3d69d507d017100a262efb5bd856a7b667a2b19
        with:
          shell: powershell
          eventId: "DO0092"
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
